# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

# Pre-build hooks
before:
  hooks:
    - go mod tidy
    - go generate ./...

# Build configuration
builds:
  - id: toshi
    main: main.go
    binary: toshi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# Archive configuration
archives:
  - id: toshi-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

# Generate checksum file
checksum:
  name_template: "checksums.txt"

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Release configuration
release:
  github:
    owner: mfkd
    name: toshi